# This playbook automates the entire process of installing Docker on a Debian server,
# making it easy to set up and manage Docker environments across multiple servers.
#
# Requieres a list of [install_docker] in a hosts file.
#
# Disables docker to use iptables.
#
# ansible-playbook -i hosts playbooks/apps/install_docker.yml --ask-become-pass
---
- name: Install Docker
  hosts: install_docker
  become: true
  # Ask if it's Debian or Ubuntu
  vars_prompt:
    - name: distribution_choice
      prompt: "Is the system Debian or Ubuntu? (Enter 'debian' or 'ubuntu')"
      private: false
  tasks:
    - name: Validate input
      ansible.builtin.fail:
        msg: "Invalid distribution choice. Please enter 'debian' or 'ubuntu'."
      when: distribution_choice | lower not in ['debian', 'ubuntu']

    - name: Update packages
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
      when: distribution_choice | lower == 'debian'

    - name: Add Docker apt repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        create: true
        mode: "0644"
      when: distribution_choice | lower == 'debian'

    # Uncomment for Ubuntu
    - name: Install Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
      when: distribution_choice | lower == 'ubuntu'

    - name: Add Docker apt repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        create: true
        mode: "0644"
      when: distribution_choice | lower == 'ubuntu'

    - name: Update apt package index again
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
